export const UPLOAD_DATA = "UPLOAD_DATA";
export const GET_ID_PRODUCT = "GET_ID_PRODUCT";
export const GET_REVIEW_INFO = "GET_REVIEW_INFO";
export const UPLOAD_REVIEW_SUCCESS = "UPLOAD_REVIEW_SUCCESS";
export const UPLOAD_REVIEW_ERROR = "UPLOAD_REVIEW_SUCCESS";