export const SEND_LOAD_DATA = "SEND_LOAD_DATA";
export const UPLOAD_REVIEW = "UPLOAD_REVIEW";
export const UPLOAD_REVIEW_SUCCESS = "UPLOAD_REVIEW_SUCCESS";
export const UPLOAD_REVIEW_ERROR = "UPLOAD_REVIEW_ERROR";
export const CLOSE_REVIEW_FORM = "CLOSE_REVIEW_FORM";